set -a terminal-features "tmux-256color:RGB"
set -g prefix C-SPACE
set -g base-index 1
set -g renumber-windows on   
set -g mode-keys vi
set -g status-position top
set -g status-justify absolute-centre
set -g status-style "bg=default"
set -g status-left-style "fg=blue bold"
set -g status-left "#S"
set -g status-right ""
set -g window-status-current-style "fg=blue bold"
set -g message-style "bg=blue,fg=black"
set -g mouse on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Search Mode VI
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -selection clipboard -i'
bind P paste-buffer

bind r source-file ~/.config/tmux/tmux.conf \; display-message "Reloaded tmux.conf"
bind f run-shell "tmux neww ~/.config/scripts/tmux-session-dispensary.sh"
bind a send-keys 'source "$(find . -path "*/bin/activate" -type f | sk)"' C-m

bind  %  split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind  c  new-window      -c "#{pane_current_path}"

run '~/.tmux/plugins/tpm/tpm'
